---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include=FALSE}
library(radsets)
library(tidyverse)
library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    x = paste(x, collapse = '.')
    if (!grepl('\\.svg', x)) return(hook_plot(x, options))
    # read the content of the svg image and write it out without <?xml ... ?>
    paste(readLines(x)[-1], collapse = '\n')
  })
})
```

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

### Overview

The **radsets** package creates Radial Sets diagrams for visualizating overlapping sets. 

```{r, echo = FALSE, dev = 'svg'}
# Load sample data
data("movieSets")

# Define set names (user specified)
setNames <- movieSets %>%
  select(Action:Western) %>%
  colnames()

# Define ID column (user specified)
idName <- "movieId"

# Define max degree (user specified)
maxDegree <- 4

# Calculate set sizes
setSizes <-
  getSetSizes(movieSets, setNames)

# Calculate set sizes by degree
setSizesByDegree <-
  getSetSizesByDegree(movieSets, setNames, idName)

# Calculate edge data
setIntersections <-
  getSetIntersections(movieSets, setNames, idName)

buildRadialSetsPlot(
  setSizes,
  setSizesByDegree,
  setIntersections,
  setOrder = c("Drama", "Romance", "Comedy", "Musical", "Animation", "Children", 
               "Fantasy", "Adventure", "Action", "War", "Sci-Fi", "Horror", 
               "Crime", "Thriller", "Mystery", "IMAX", "Western", "Film-Noir", 
               "Documentary"),
  disPropLim = c(-1, 1)
)
```